### ISSUE TITLE
Cannot find module express/node_modules/cookie

### ISSUE THREAD

**Issue by grzaks** [robksawyer/merchit#1]
I cloned git repo, installed nodejs/npm from scratch on my macos, did `npm install` and `node app.js` fails with

```
module.js:544
    throw err;
    ^

Error: Cannot find module 'express/node_modules/cookie'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/gaks/merchit/node_modules/sails/lib/hooks/session/index.js:9:12)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at /Users/gaks/merchit/node_modules/sails/lib/app/configuration/index.js:54:28
    at Function.reduce (/Users/gaks/merchit/node_modules/lodash/dist/lodash.js:3735:25)
    at Configuration.defaultConfig (/Users/gaks/merchit/node_modules/sails/lib/app/configuration/index.js:53:18)
    at Configuration.bound [as defaults] (/Users/gaks/merchit/node_modules/lodash/dist/lodash.js:729:21)
```

Environment:
```
$ node -v
v9.2.0
$ npm -v
5.5.1
```

Any hints?

**Comment by robksawyer** [comment]
Yep, just need to install the cookie node module. Apparently, I forgot to add this to the package. Use `npm install cookie` or `yarn add cookie` to do so.
